# name of your github action
name: ForkBoard Build
# this will help you specify where to run 
on:
  # enable manual execution
  workflow_dispatch:
env:
  FBVERSION: 1.1.1
  RELEASETAG: v1.1.1
# this is where the magic happens, each job happens in parallel btw
jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 16.15.1
    - name: see NPM Reinstall
      run: yarn install
    - name: Install Electron Installer Windows
      run: yarn add electron-installer-windows@^3.0.0
    - name: Build ForkBoard
      run: yarn package-win
    - name: Package ForkBoard
      run: yarn installer-win
    - name: rename output articfact
      run: mv ./dist/ForkBoard-$env:FBVERSION-setup.exe ./dist/ForkBoard-$env:FBVERSION-x64.exe
    - name: Upload release binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ github.token }}
        file: ./dist/ForkBoard-1.1.1-x64.exe
        asset_name: ForkBoard-1.1.1-x64.exe
        tag: v1.1.1
        overwrite: true
  build_on_mac_arm64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 16.15.1
    - name: see NPM Reinstall
      run: yarn install
    - name: Install Electron Installer Mac
      run: yarn add electron-installer-dmg@^4.0.0
    - name: Build ForkBoard for Mac (arm64)
      run: yarn package-mac-arm64
    - name: Package ForkBoard for Mac (arm64)
      run: yarn installer-mac-arm64
    - name: rename output artifact (arm64)
      run: mv ./dist/ForkBoard.dmg ./dist/ForkBoard-$FBVERSION-arm64.dmg
    - name: Upload release binary (arm64)
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ github.token }}
        file: ./dist/ForkBoard-1.1.1-arm64.dmg
        asset_name: ForkBoard-1.1.1-arm64.dmg
        tag: v1.1.1
        overwrite: true
  build_on_mac_x64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 16.15.1
    - name: see NPM Reinstall
      run: yarn install
    - name: Install Electron Installer Mac
      run: yarn add electron-installer-dmg@^4.0.0
    - name: Build ForkBoard for Mac (x64)
      run: yarn package-mac-x64
    - name: Package ForkBoard for Mac (x64)
      run: yarn installer-mac-x64
    - name: rename output artifact (x64)
      run: mv ./dist/ForkBoard.dmg ./dist/ForkBoard-$FBVERSION-x64.dmg
    - name: Upload release binary (x64)
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ github.token }}
        file: ./dist/ForkBoard-1.1.1-x64.dmg
        asset_name: ForkBoard-1.1.1-x64.dmg
        tag: v1.1.1
        overwrite: true
  build_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 16.15.1
    - name: see NPM Reinstall
      run: yarn install
    - name: Install Electron Installer Debian
      run: yarn add electron-installer-debian@^3.1.0
    - name: Build ForkBoard for Ubuntu
      run: yarn package-deb
    - name: Package ForkBoard for Ubuntu
      run: yarn installer-deb
    - name: rename output articfact
      run: mv ./dist/forkboard_1.1.1_amd64.deb ./dist/ForkBoard-$FBVERSION-x64.deb
    - name: Upload release binary (arm64)
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ github.token }}
        file: ./dist/ForkBoard-1.1.1-x64.deb
        asset_name: ForkBoard-1.1.1-x64.deb
        tag: v1.1.1
        overwrite: true
  