# name of your github action
name: ForkBoard Build
# this will help you specify where to run 
on:
  # enable manual execution
  workflow_dispatch:
# this is where the magic happens, each job happens in parallel btw
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 16.15.1
    - name: see directory
      run: ls
    - name: Install Electron
      run: npm i electron@15.3.3
    - name: Install Electron Packager
      run: npm i electron-packager
    - name: Install Electron Installer DMG
      run: npm i electron-installer-dmg
    - name: Install ElectronLog
      run: npm i electron-log
    - name: Install Chart.JS
      run: npm i chart.js@3.9.1
    - name: Install Axios
      run: npm i axios@0.24.0
    - name: see Install Electron Prompt
      run:  npm i electron-prompt@1.7.0
    - name: Build ForkBoard
      run: electron-packager . ForkBoard --darwin --arm64 --out dist/ --icon=assets/icons/fork-board-gray.icns --overwrite=true
    - name: Package ForkBoard
      run: electron-packager . ForkBoard --darwin --arm64 --out dist/ --icon=assets/icons/fork-board-gray.icns --overwrite=true
    - name: see directory
      run: ls ./dist