# name of your github action
name: ForkBoard Build
# this will help you specify where to run 
on:
  # enable manual execution
  workflow_dispatch:
# this is where the magic happens, each job happens in parallel btw
jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 16.15.1
    - name: see directory
      run: ls
#    - name: Install Electron
#      run: npm install --global electron@15.3.3
#    - name: Install Electron Packager
#      run: npm install --global electron-packager
#    - name: Install Electron Installer DMG
#      run: npm install --global electron-installer-dmg
#    - name: Install ElectronLog
#      run: npm install --global electron-log
#    - name: Install Chart.JS
#      run: npm install --global chart.js@3.9.1
#    - name: Install Axios
#      run: npm install --global axios@0.24.0
#    - name: see Install Electron Prompt
#      run: npm install --global electron-prompt@1.7.0
    - name: see NPM Reinstall
      run: yarn install
    - name: Install Electron Installer Windows
      run: yarn add electron-installer-windows@^3.0.0
    - name: Build ForkBoard
      run: yarn package-win
    - name: Package ForkBoard
      run: yarn installer-win
    - name: see out directory
      run: ls ./out
    - name: see installers directory
      run: ls ./out/installers