# name of your github action
name: ForkBoard Build
# this will help you specify where to run 
on:
  # enable manual execution
  workflow_dispatch:
# this is where the magic happens, each job happens in parallel btw
jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 16.15.1
    - name: see directory
      run: ls
    - name: see NPM Reinstall
      run: yarn install
    - name: Install Electron Installer Windows
      run: yarn add electron-installer-windows@^3.0.0
    - name: Build ForkBoard
      run: yarn package-win
    - name: Package ForkBoard
      run: yarn installer-win
    - name: see out directory
      run: ls ./out/win
    artifacts:
      paths:
        - ./out/win/*

  build_on_mac_arm64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 16.15.1
    - name: see directory
      run: ls
    - name: see NPM Reinstall
      run: yarn install
    - name: Install Electron Installer Mac
      run: yarn add electron-installer-dmg@^4.0.0
    - name: Build ForkBoard for Mac (arm64)
      run: yarn package-mac-arm64
    - name: Package ForkBoard for Mac (arm64)
      run: yarn installer-mac-arm64
    - name: see dist directory
      run: ls ./out/arm64

  build_on_mac_x64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 16.15.1
    - name: see directory
      run: ls
    - name: see NPM Reinstall
      run: yarn install
    - name: Install Electron Installer Mac
      run: yarn add electron-installer-dmg@^4.0.0
    - name: Build ForkBoard for Mac (x64)
      run: yarn package-mac-x64
    - name: Package ForkBoard for Mac (x64)
      run: yarn installer-mac-x64
    - name: see dist directory
      run: ls ./out/x64

  build_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 16.15.1
    - name: see directory
      run: ls
    - name: see NPM Reinstall
      run: yarn install
    - name: Install Electron Installer Debian
      run: yarn add electron-installer-debian@^3.1.0
    - name: Build ForkBoard for Ubuntu
      run: yarn package-deb
    - name: Package ForkBoard for Ubuntu
      run: yarn installer-deb
    - name: see out directory
      run: ls ./out/deb
  