# name of your github action
name: ForkBoard Build
# this will help you specify where to run 
on:
  # enable manual execution
  workflow_dispatch:
# this is where the magic happens, each job happens in parallel btw
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 16.15.1
    - name: see directory
      run: ls
    - name: Install dependencies
      run: yarn install
    - name: Install dependencies
      run: yarn install
    - name: check env
      env:
        ELECTRON: true
        APP_VERSION_NUMBER: 1.1.1
      run: set
    - name: Build on Windows
      env:
        ELECTRON: true
        APP_VERSION_NUMBER: 1.1.1
      run: yarn build
    - name: Build Electron
      env:
        ELECTRON: true
        APP_VERSION_NUMBER: 1.1.1
      run: yarn electron:buildWin
    - name: see directory
      run: ls
    - name: see directory
      run: ls ./electron_dist/squirrel-windows
